### ISSUE TITLE
Does the terraform provider version support Anzure Native Bastion with Standard SKU?

### ISSUE THREAD

**Issue by vishalmaheswari** [kumarvna/terraform-azurerm-azure-bastion#6]

**Comment by kumarvna** [comment]
Not yet.  Microsoft announced the Public Preview of Bastion Standard SKU last month, and those changes are yet to come to the terraform.  They are generally available once services are in GA. I will update the module once they are available.  This module creates Bastion service with the 'Basic' tier.
